# -*- mode: python ; coding: utf-8 -*-
import os

a = Analysis(
    ['meshmill.py'],
    pathex=[],
    binaries=[],
    datas=[
        ('LICENSE', '.'),
        ('README.md', '.'),
        ('ROADMAP.md', '.'),
        ('THIRD_PARTY_NOTICES.md', '.'),
        ('docs/OUT_OF_CORE.md', 'docs'),
        ('assets/meshmill-mark.svg', 'assets'),
        ('assets/meshmill-logo.svg', 'assets'),
        ('locales', 'locales'),
    ],
    hiddenimports=[
        'vtkmodules.vtkInteractionStyle',
        'vtkmodules.vtkRenderingOpenGL2',
        'vtkmodules.vtkRenderingFreeType',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=['matplotlib', 'pandas', 'scipy'],
    noarchive=False,
    optimize=1,
)
pyz = PYZ(a.pure)
gui = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name='MeshMill',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    console=False,
    version=os.path.join(SPECPATH, 'version_info.txt'),
    icon=os.path.join(SPECPATH, 'assets', 'meshmill.ico'),
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
cli = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name='MeshMillCLI',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    console=True,
    version=os.path.join(SPECPATH, 'version_info.txt'),
    icon=os.path.join(SPECPATH, 'assets', 'meshmill.ico'),
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
coll = COLLECT(
    gui,
    cli,
    a.binaries,
    a.datas,
    strip=False,
    upx=True,
    upx_exclude=[],
    name='MeshMill',
)
